---
- name: Loop create fw rules where app-id is used with nonstandard port.
  # Each appid with a nonstandard service must be it's own rule.
  # Todo - append non standard ports to appid w nonstandard port where source and dest and app are identical.
  panos_security_rule:
    ip_address: "{{ ip_address }}"
    api_key: "{{ api_string }}"
    device_group: "{{ device_group_to_conf }}"
    state: present
    rule_name: "{{ rule_name_nonstandard_app_service }}_{{ appid_nonstandard_port_list_loop_counter | string }}"
    description: "{{ cr_line.desc }}"
    source_ip: "{{ source_address_list_to_conf }}"
    source_user: "{{ source_user_list_to_conf }}"
    destination_ip: "{{ dest_address_list_to_conf }}"
    application: "{{ item.0 }}"
    service: "{{ item.1 }}"
    tag_name: ["{{ cr_line.cr_tag_name }}"]
    rulebase: "{{ palo_rulebase }}"
    log_setting: "{{ palo_logging_profile }}"
    group_profile: "{{ security_profile_to_conf }}"
    source_zone: "{{ source_zones_to_conf }}"
    destination_zone: "{{ dest_zones_to_conf }}"
    action: 'allow'
    commit: false
  when: ((applications_appid_nonstandard_port_list | length) > 0)

- name: Increment loop counter for appid/non standard port subloop.
  # this counter is used to assign unique rule names
  set_fact:
    appid_nonstandard_port_list_loop_counter: "{{ (appid_nonstandard_port_list_loop_counter|int + 1) }}"
